theme = "slick" 
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MiB/{MTg} GiB"

[[block]]
block = "custom"
on_click = "cd Pictures;scrot"
command = "echo " 

[[block]]
block  = "battery"

[[block]]
block = "sound"

[[block]]
block = "pacman"

[[block]]
block = "music"
player = "pragha"
buttons = ["prev", "play", "next"]

[[block]]
block = "time"
format = "%a %m/%d %R"

[[block]]
block = "custom"
command = "iwgetid -r"
interval = 5
on_click = "terminator -e nmtui"

[[block]]
block = "custom"
command = "echo   Tools"
on_click = "revenge-tools"
